#ifndef __FLASH_H
#define __FLASH_H

#include <stdint.h>

//关于flash布局的说明
#define FLASH_BASE_ADDR	0x00000000			/* Flash基地址 */
#define	FLASH_SIZE		(64*1024)		    /* Flash 容量 */

/* Base address of the Flash sectors */
#define EACH_SECTOR_SIZE    (512)        /* 每个扇叶的大小 */
/* 所有的扇叶 */
typedef enum
{
    FLASH_Sector_0 = 0,
    FLASH_Sector_1,
    FLASH_Sector_2,
    FLASH_Sector_3,
    FLASH_Sector_4,
    FLASH_Sector_5,
    FLASH_Sector_6,
    FLASH_Sector_7,
    FLASH_Sector_8,
    FLASH_Sector_9,
    FLASH_Sector_10,
    FLASH_Sector_11,
    FLASH_Sector_12,
    FLASH_Sector_13,
    FLASH_Sector_14,
    FLASH_Sector_15,
    FLASH_Sector_16,
    FLASH_Sector_17,
    FLASH_Sector_18,
    FLASH_Sector_19,
    FLASH_Sector_20,
    FLASH_Sector_21,
    FLASH_Sector_22,
    FLASH_Sector_23,
    FLASH_Sector_24,
    FLASH_Sector_25,
    FLASH_Sector_26,
    FLASH_Sector_27,
    FLASH_Sector_28,
    FLASH_Sector_29,
    FLASH_Sector_30,
    FLASH_Sector_31,
    FLASH_Sector_32,
    FLASH_Sector_33,
    FLASH_Sector_34,
    FLASH_Sector_35,
    FLASH_Sector_36,
    FLASH_Sector_37,
    FLASH_Sector_38,
    FLASH_Sector_39,
    FLASH_Sector_40,
    FLASH_Sector_41,
    FLASH_Sector_42,
    FLASH_Sector_43,
    FLASH_Sector_44,
    FLASH_Sector_45,
    FLASH_Sector_46,
    FLASH_Sector_47,
    FLASH_Sector_48,
    FLASH_Sector_49,
    FLASH_Sector_50,
    FLASH_Sector_51,
    FLASH_Sector_52,
    FLASH_Sector_53,
    FLASH_Sector_54,
    FLASH_Sector_55,
    FLASH_Sector_56,
    FLASH_Sector_57,
    FLASH_Sector_58,
    FLASH_Sector_59,
    FLASH_Sector_60,
    FLASH_Sector_61,
    FLASH_Sector_62,
    FLASH_Sector_63,
    FLASH_Sector_64,
    FLASH_Sector_65,
    FLASH_Sector_66,
    FLASH_Sector_67,
    FLASH_Sector_68,
    FLASH_Sector_69,
    FLASH_Sector_70,
    FLASH_Sector_71,
    FLASH_Sector_72,
    FLASH_Sector_73,
    FLASH_Sector_74,
    FLASH_Sector_75,
    FLASH_Sector_76,
    FLASH_Sector_77,
    FLASH_Sector_78,
    FLASH_Sector_79,
    FLASH_Sector_80,
    FLASH_Sector_81,
    FLASH_Sector_82,
    FLASH_Sector_83,
    FLASH_Sector_84,
    FLASH_Sector_85,
    FLASH_Sector_86,
    FLASH_Sector_87,
    FLASH_Sector_88,
    FLASH_Sector_89,
    FLASH_Sector_90,
    FLASH_Sector_91,
    FLASH_Sector_92,
    FLASH_Sector_93,
    FLASH_Sector_94,
    FLASH_Sector_95,
    FLASH_Sector_96,
    FLASH_Sector_97,
    FLASH_Sector_98,
    FLASH_Sector_99,
    FLASH_Sector_100,
    FLASH_Sector_101,
    FLASH_Sector_102,
    FLASH_Sector_103,
    FLASH_Sector_104,
    FLASH_Sector_105,
    FLASH_Sector_106,
    FLASH_Sector_107,
    FLASH_Sector_108,
    FLASH_Sector_109,
    FLASH_Sector_110,
    FLASH_Sector_111,
    FLASH_Sector_112,
    FLASH_Sector_113,
    FLASH_Sector_114,
    FLASH_Sector_115,
    FLASH_Sector_116,
    FLASH_Sector_117,
    FLASH_Sector_118,
    FLASH_Sector_119,
    FLASH_Sector_120,
    FLASH_Sector_121,
    FLASH_Sector_122,
    FLASH_Sector_123,
    FLASH_Sector_124,
    FLASH_Sector_125,
    FLASH_Sector_126,
    FLASH_Sector_127,
}FLASH_SECTOR;

uint8_t Flash_write(uint32_t Add, uint8_t* dataIn, uint32_t dataSize);
uint8_t Flash_erase(uint32_t sectorNum);
uint8_t Flash_read(uint32_t Addr, uint8_t* readBuff, uint32_t dataSize);

#endif